export const mockdata = [
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3Mcii5XWf6E0lrY3Uky4cA"
          },
          href: "https://api.spotify.com/v1/artists/3Mcii5XWf6E0lrY3Uky4cA",
          id: "3Mcii5XWf6E0lrY3Uky4cA",
          name: "Ice Cube",
          type: "artist",
          uri: "spotify:artist:3Mcii5XWf6E0lrY3Uky4cA"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/3xbWu3mLkkWZvgHtExIaKZ"
      },
      href: "https://api.spotify.com/v1/albums/3xbWu3mLkkWZvgHtExIaKZ",
      id: "3xbWu3mLkkWZvgHtExIaKZ",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273e83d58253e2e7c6742bbf9e4",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02e83d58253e2e7c6742bbf9e4",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851e83d58253e2e7c6742bbf9e4",
          width: 64
        }
      ],
      name: "Raw Footage",
      release_date: "2008-01-01",
      release_date_precision: "day",
      total_tracks: 16,
      type: "album",
      uri: "spotify:album:3xbWu3mLkkWZvgHtExIaKZ"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3Mcii5XWf6E0lrY3Uky4cA"
        },
        href: "https://api.spotify.com/v1/artists/3Mcii5XWf6E0lrY3Uky4cA",
        id: "3Mcii5XWf6E0lrY3Uky4cA",
        name: "Ice Cube",
        type: "artist",
        uri: "spotify:artist:3Mcii5XWf6E0lrY3Uky4cA"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 281653,
    explicit: true,
    external_ids: {
      isrc: "USNPD0714889"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/62duQFVb51gug9ajR6Qdiz"
    },
    href: "https://api.spotify.com/v1/tracks/62duQFVb51gug9ajR6Qdiz",
    id: "62duQFVb51gug9ajR6Qdiz",
    is_local: false,
    name: "Gangsta Rap Made Me Do It",
    popularity: 64,
    preview_url: null,
    track_number: 4,
    type: "track",
    uri: "spotify:track:62duQFVb51gug9ajR6Qdiz"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh"
          },
          href: "https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh",
          id: "3q7HBObVc0L8jNeTe5Gofh",
          name: "50 Cent",
          type: "artist",
          uri: "spotify:artist:3q7HBObVc0L8jNeTe5Gofh"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "TJ",
        "VE",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/6aAGx3HGsNoWvn6rMRHXBm"
      },
      href: "https://api.spotify.com/v1/albums/6aAGx3HGsNoWvn6rMRHXBm",
      id: "6aAGx3HGsNoWvn6rMRHXBm",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2734f3b851619040434f6ba58c4",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e024f3b851619040434f6ba58c4",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048514f3b851619040434f6ba58c4",
          width: 64
        }
      ],
      name: "Curtis",
      release_date: "2007-01-01",
      release_date_precision: "day",
      total_tracks: 17,
      type: "album",
      uri: "spotify:album:6aAGx3HGsNoWvn6rMRHXBm"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh"
        },
        href: "https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh",
        id: "3q7HBObVc0L8jNeTe5Gofh",
        name: "50 Cent",
        type: "artist",
        uri: "spotify:artist:3q7HBObVc0L8jNeTe5Gofh"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "TJ",
      "VE",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 192080,
    explicit: true,
    external_ids: {
      isrc: "USUM70735432"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/4KxIW9rRwmQYb27ya4HGiI"
    },
    href: "https://api.spotify.com/v1/tracks/4KxIW9rRwmQYb27ya4HGiI",
    id: "4KxIW9rRwmQYb27ya4HGiI",
    is_local: false,
    name: "My Gun Go Off",
    popularity: 45,
    preview_url: null,
    track_number: 2,
    type: "track",
    uri: "spotify:track:4KxIW9rRwmQYb27ya4HGiI"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/59wfkuBoNyhDMQGCljbUbA"
          },
          href: "https://api.spotify.com/v1/artists/59wfkuBoNyhDMQGCljbUbA",
          id: "59wfkuBoNyhDMQGCljbUbA",
          name: "Diddy",
          type: "artist",
          uri: "spotify:artist:59wfkuBoNyhDMQGCljbUbA"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/4OGaOZUHLhSeiicZB909aL"
      },
      href: "https://api.spotify.com/v1/albums/4OGaOZUHLhSeiicZB909aL",
      id: "4OGaOZUHLhSeiicZB909aL",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2736af4bd99c9a95bbc008c53c4",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e026af4bd99c9a95bbc008c53c4",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048516af4bd99c9a95bbc008c53c4",
          width: 64
        }
      ],
      name: "No Way Out",
      release_date: "1997",
      release_date_precision: "year",
      total_tracks: 17,
      type: "album",
      uri: "spotify:album:4OGaOZUHLhSeiicZB909aL"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/59wfkuBoNyhDMQGCljbUbA"
        },
        href: "https://api.spotify.com/v1/artists/59wfkuBoNyhDMQGCljbUbA",
        id: "59wfkuBoNyhDMQGCljbUbA",
        name: "Diddy",
        type: "artist",
        uri: "spotify:artist:59wfkuBoNyhDMQGCljbUbA"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1wiBLzTI7z9RUwEpNPdFT6"
        },
        href: "https://api.spotify.com/v1/artists/1wiBLzTI7z9RUwEpNPdFT6",
        id: "1wiBLzTI7z9RUwEpNPdFT6",
        name: "Mase",
        type: "artist",
        uri: "spotify:artist:1wiBLzTI7z9RUwEpNPdFT6"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 231160,
    explicit: true,
    external_ids: {
      isrc: "USBB40580687"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/1EM23A621Z0QyTlWKu7T1l"
    },
    href: "https://api.spotify.com/v1/tracks/1EM23A621Z0QyTlWKu7T1l",
    id: "1EM23A621Z0QyTlWKu7T1l",
    is_local: false,
    name: "Can't Nobody Hold Me Down (feat. Mase)",
    popularity: 61,
    preview_url: "https://p.scdn.co/mp3-preview/89db36fad0b611672f5cf70f7bd602a5d80a2746?cid=e2ce5956a54142e3954a58845c7b9319",
    track_number: 17,
    type: "track",
    uri: "spotify:track:1EM23A621Z0QyTlWKu7T1l"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0NbfKEOTQCcwd6o7wSDOHI"
          },
          href: "https://api.spotify.com/v1/artists/0NbfKEOTQCcwd6o7wSDOHI",
          id: "0NbfKEOTQCcwd6o7wSDOHI",
          name: "The Game",
          type: "artist",
          uri: "spotify:artist:0NbfKEOTQCcwd6o7wSDOHI"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/4PrPbmm0gKvaD3rerOXFg8"
      },
      href: "https://api.spotify.com/v1/albums/4PrPbmm0gKvaD3rerOXFg8",
      id: "4PrPbmm0gKvaD3rerOXFg8",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273b1d860ab1ba847e778b2796d",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02b1d860ab1ba847e778b2796d",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851b1d860ab1ba847e778b2796d",
          width: 64
        }
      ],
      name: "The Documentary",
      release_date: "2005",
      release_date_precision: "year",
      total_tracks: 18,
      type: "album",
      uri: "spotify:album:4PrPbmm0gKvaD3rerOXFg8"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0NbfKEOTQCcwd6o7wSDOHI"
        },
        href: "https://api.spotify.com/v1/artists/0NbfKEOTQCcwd6o7wSDOHI",
        id: "0NbfKEOTQCcwd6o7wSDOHI",
        name: "The Game",
        type: "artist",
        uri: "spotify:artist:0NbfKEOTQCcwd6o7wSDOHI"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh"
        },
        href: "https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh",
        id: "3q7HBObVc0L8jNeTe5Gofh",
        name: "50 Cent",
        type: "artist",
        uri: "spotify:artist:3q7HBObVc0L8jNeTe5Gofh"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 235533,
    explicit: true,
    external_ids: {
      isrc: "USIR10400834"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/4PmMVdIFpJTB9WQbmILf4p"
    },
    href: "https://api.spotify.com/v1/tracks/4PmMVdIFpJTB9WQbmILf4p",
    id: "4PmMVdIFpJTB9WQbmILf4p",
    is_local: false,
    name: "How We Do",
    popularity: 79,
    preview_url: null,
    track_number: 6,
    type: "track",
    uri: "spotify:track:4PmMVdIFpJTB9WQbmILf4p"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
          },
          href: "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
          id: "5K4W6rqBFWDnAN6FQUkS6x",
          name: "Kanye West",
          type: "artist",
          uri: "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/4Uv86qWpGTxf7fU7lG5X6F"
      },
      href: "https://api.spotify.com/v1/albums/4Uv86qWpGTxf7fU7lG5X6F",
      id: "4Uv86qWpGTxf7fU7lG5X6F",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b27325b055377757b3cdd6f26b78",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e0225b055377757b3cdd6f26b78",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d0000485125b055377757b3cdd6f26b78",
          width: 64
        }
      ],
      name: "The College Dropout",
      release_date: "2004-02-10",
      release_date_precision: "day",
      total_tracks: 21,
      type: "album",
      uri: "spotify:album:4Uv86qWpGTxf7fU7lG5X6F"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
        },
        href: "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
        id: "5K4W6rqBFWDnAN6FQUkS6x",
        name: "Kanye West",
        type: "artist",
        uri: "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1lE6SEy8f84Zhjvp7r8yTD"
        },
        href: "https://api.spotify.com/v1/artists/1lE6SEy8f84Zhjvp7r8yTD",
        id: "1lE6SEy8f84Zhjvp7r8yTD",
        name: "Syleena Johnson",
        type: "artist",
        uri: "spotify:artist:1lE6SEy8f84Zhjvp7r8yTD"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 223506,
    explicit: true,
    external_ids: {
      isrc: "USDJ20301703"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/5SkRLpaGtvYPhw02vZhQQ9"
    },
    href: "https://api.spotify.com/v1/tracks/5SkRLpaGtvYPhw02vZhQQ9",
    id: "5SkRLpaGtvYPhw02vZhQQ9",
    is_local: false,
    name: "All Falls Down",
    popularity: 86,
    preview_url: null,
    track_number: 4,
    type: "track",
    uri: "spotify:track:5SkRLpaGtvYPhw02vZhQQ9"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR"
          },
          href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
          id: "7dGJo4pcD2V6oG8kP0tJRR",
          name: "Eminem",
          type: "artist",
          uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/6EzbFdrwvWpnpUjzrR57aU"
      },
      href: "https://api.spotify.com/v1/albums/6EzbFdrwvWpnpUjzrR57aU",
      id: "6EzbFdrwvWpnpUjzrR57aU",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273a18291a1854b9b6371ff9663",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02a18291a1854b9b6371ff9663",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851a18291a1854b9b6371ff9663",
          width: 64
        }
      ],
      name: "The Eminem Show (Expanded Edition)",
      release_date: "2022-05-26",
      release_date_precision: "day",
      total_tracks: 38,
      type: "album",
      uri: "spotify:album:6EzbFdrwvWpnpUjzrR57aU"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR"
        },
        href: "https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR",
        id: "7dGJo4pcD2V6oG8kP0tJRR",
        name: "Eminem",
        type: "artist",
        uri: "spotify:artist:7dGJo4pcD2V6oG8kP0tJRR"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/50UMTib697JJ44le8DO2Va"
        },
        href: "https://api.spotify.com/v1/artists/50UMTib697JJ44le8DO2Va",
        id: "50UMTib697JJ44le8DO2Va",
        name: "Tony Yayo",
        type: "artist",
        uri: "spotify:artist:50UMTib697JJ44le8DO2Va"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh"
        },
        href: "https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh",
        id: "3q7HBObVc0L8jNeTe5Gofh",
        name: "50 Cent",
        type: "artist",
        uri: "spotify:artist:3q7HBObVc0L8jNeTe5Gofh"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3vDUJHQtqT3jFRZ2ECXDTi"
        },
        href: "https://api.spotify.com/v1/artists/3vDUJHQtqT3jFRZ2ECXDTi",
        id: "3vDUJHQtqT3jFRZ2ECXDTi",
        name: "Lloyd Banks",
        type: "artist",
        uri: "spotify:artist:3vDUJHQtqT3jFRZ2ECXDTi"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 281457,
    explicit: true,
    external_ids: {
      isrc: "USIR10312000"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/4OYGHze5MiMkgozardIRxU"
    },
    href: "https://api.spotify.com/v1/tracks/4OYGHze5MiMkgozardIRxU",
    id: "4OYGHze5MiMkgozardIRxU",
    is_local: false,
    name: "Bump Heads",
    popularity: 70,
    preview_url: null,
    track_number: 23,
    type: "track",
    uri: "spotify:track:4OYGHze5MiMkgozardIRxU"
  },
  {
    album: {
      album_type: "COMPILATION",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
          },
          href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
          id: "0LyfQWJT6nXafLPZqxe9Of",
          name: "Various Artists",
          type: "artist",
          uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5D2CHiTlb8MXWJsZWXjkZf"
      },
      href: "https://api.spotify.com/v1/albums/5D2CHiTlb8MXWJsZWXjkZf",
      id: "5D2CHiTlb8MXWJsZWXjkZf",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b27369da799626c944aeef9b5e37",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e0269da799626c944aeef9b5e37",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d0000485169da799626c944aeef9b5e37",
          width: 64
        }
      ],
      name: "Get Rich Or Die Tryin'- The Original Motion Picture Soundtrack",
      release_date: "2005-01-01",
      release_date_precision: "day",
      total_tracks: 18,
      type: "album",
      uri: "spotify:album:5D2CHiTlb8MXWJsZWXjkZf"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh"
        },
        href: "https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh",
        id: "3q7HBObVc0L8jNeTe5Gofh",
        name: "50 Cent",
        type: "artist",
        uri: "spotify:artist:3q7HBObVc0L8jNeTe5Gofh"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 221666,
    explicit: true,
    external_ids: {
      isrc: "USUM70504544"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/75Dad3cKI6kduvpNbr2Fu6"
    },
    href: "https://api.spotify.com/v1/tracks/75Dad3cKI6kduvpNbr2Fu6",
    id: "75Dad3cKI6kduvpNbr2Fu6",
    is_local: false,
    name: "Talk About Me",
    popularity: 46,
    preview_url: null,
    track_number: 15,
    type: "track",
    uri: "spotify:track:75Dad3cKI6kduvpNbr2Fu6"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2wIVse2owClT7go1WT98tk"
          },
          href: "https://api.spotify.com/v1/artists/2wIVse2owClT7go1WT98tk",
          id: "2wIVse2owClT7go1WT98tk",
          name: "Missy Elliott",
          type: "artist",
          uri: "spotify:artist:2wIVse2owClT7go1WT98tk"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/6vV5UrXcfyQD1wu4Qo2I9K"
      },
      href: "https://api.spotify.com/v1/albums/6vV5UrXcfyQD1wu4Qo2I9K",
      id: "6vV5UrXcfyQD1wu4Qo2I9K",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273f1dfae21eaac0d24fb3dcf5a",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02f1dfae21eaac0d24fb3dcf5a",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851f1dfae21eaac0d24fb3dcf5a",
          width: 64
        }
      ],
      name: "The Cookbook",
      release_date: "2005-07-04",
      release_date_precision: "day",
      total_tracks: 16,
      type: "album",
      uri: "spotify:album:6vV5UrXcfyQD1wu4Qo2I9K"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/2wIVse2owClT7go1WT98tk"
        },
        href: "https://api.spotify.com/v1/artists/2wIVse2owClT7go1WT98tk",
        id: "2wIVse2owClT7go1WT98tk",
        name: "Missy Elliott",
        type: "artist",
        uri: "spotify:artist:2wIVse2owClT7go1WT98tk"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/2NdeV5rLm47xAvogXrYhJX"
        },
        href: "https://api.spotify.com/v1/artists/2NdeV5rLm47xAvogXrYhJX",
        id: "2NdeV5rLm47xAvogXrYhJX",
        name: "Ciara",
        type: "artist",
        uri: "spotify:artist:2NdeV5rLm47xAvogXrYhJX"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/15GGbJKqC6w0VYyAJtjej6"
        },
        href: "https://api.spotify.com/v1/artists/15GGbJKqC6w0VYyAJtjej6",
        id: "15GGbJKqC6w0VYyAJtjej6",
        name: "Fatman Scoop",
        type: "artist",
        uri: "spotify:artist:15GGbJKqC6w0VYyAJtjej6"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 226863,
    explicit: true,
    external_ids: {
      isrc: "USEE10414022"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/0UaMYEvWZi0ZqiDOoHU3YI"
    },
    href: "https://api.spotify.com/v1/tracks/0UaMYEvWZi0ZqiDOoHU3YI",
    id: "0UaMYEvWZi0ZqiDOoHU3YI",
    is_local: false,
    name: "Lose Control (feat. Ciara & Fat Man Scoop)",
    popularity: 70,
    preview_url: "https://p.scdn.co/mp3-preview/253a76c453026570394aa26156691d1d81b387c0?cid=e2ce5956a54142e3954a58845c7b9319",
    track_number: 4,
    type: "track",
    uri: "spotify:track:0UaMYEvWZi0ZqiDOoHU3YI"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5spEJXLwD1sKUdC2bnOHPg"
          },
          href: "https://api.spotify.com/v1/artists/5spEJXLwD1sKUdC2bnOHPg",
          id: "5spEJXLwD1sKUdC2bnOHPg",
          name: "Bone Thugs-N-Harmony",
          type: "artist",
          uri: "spotify:artist:5spEJXLwD1sKUdC2bnOHPg"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5g2FfZVMvBqRmuHjNsaf3l"
      },
      href: "https://api.spotify.com/v1/albums/5g2FfZVMvBqRmuHjNsaf3l",
      id: "5g2FfZVMvBqRmuHjNsaf3l",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2734265ced59f64378b8a1904ad",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e024265ced59f64378b8a1904ad",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048514265ced59f64378b8a1904ad",
          width: 64
        }
      ],
      name: "Creepin on Ah Come Up",
      release_date: "1994-06-21",
      release_date_precision: "day",
      total_tracks: 8,
      type: "album",
      uri: "spotify:album:5g2FfZVMvBqRmuHjNsaf3l"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/5spEJXLwD1sKUdC2bnOHPg"
        },
        href: "https://api.spotify.com/v1/artists/5spEJXLwD1sKUdC2bnOHPg",
        id: "5spEJXLwD1sKUdC2bnOHPg",
        name: "Bone Thugs-N-Harmony",
        type: "artist",
        uri: "spotify:artist:5spEJXLwD1sKUdC2bnOHPg"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7B4hKK0S9QYnaoqa9OuwgX"
        },
        href: "https://api.spotify.com/v1/artists/7B4hKK0S9QYnaoqa9OuwgX",
        id: "7B4hKK0S9QYnaoqa9OuwgX",
        name: "Eazy-E",
        type: "artist",
        uri: "spotify:artist:7B4hKK0S9QYnaoqa9OuwgX"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 272440,
    explicit: true,
    external_ids: {
      isrc: "US23S9428107"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/1muLq1kBLWIT3pmNC2xl0g"
    },
    href: "https://api.spotify.com/v1/tracks/1muLq1kBLWIT3pmNC2xl0g",
    id: "1muLq1kBLWIT3pmNC2xl0g",
    is_local: false,
    name: "Foe Tha Love of $",
    popularity: 68,
    preview_url: "https://p.scdn.co/mp3-preview/8f1d2816fbb651eda140b8e316f0dea6440f83ea?cid=e2ce5956a54142e3954a58845c7b9319",
    track_number: 7,
    type: "track",
    uri: "spotify:track:1muLq1kBLWIT3pmNC2xl0g"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6l3HvQ5sa6mXTsMTB19rO5"
          },
          href: "https://api.spotify.com/v1/artists/6l3HvQ5sa6mXTsMTB19rO5",
          id: "6l3HvQ5sa6mXTsMTB19rO5",
          name: "J. Cole",
          type: "artist",
          uri: "spotify:artist:6l3HvQ5sa6mXTsMTB19rO5"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5FP9keIJnlSCKnkdVOf623"
      },
      href: "https://api.spotify.com/v1/albums/5FP9keIJnlSCKnkdVOf623",
      id: "5FP9keIJnlSCKnkdVOf623",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b273c1bb124f993488cf21b269fc",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e02c1bb124f993488cf21b269fc",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d00004851c1bb124f993488cf21b269fc",
          width: 64
        }
      ],
      name: "Born Sinner (Deluxe Version)",
      release_date: "2013-06-18",
      release_date_precision: "day",
      total_tracks: 21,
      type: "album",
      uri: "spotify:album:5FP9keIJnlSCKnkdVOf623"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6l3HvQ5sa6mXTsMTB19rO5"
        },
        href: "https://api.spotify.com/v1/artists/6l3HvQ5sa6mXTsMTB19rO5",
        id: "6l3HvQ5sa6mXTsMTB19rO5",
        name: "J. Cole",
        type: "artist",
        uri: "spotify:artist:6l3HvQ5sa6mXTsMTB19rO5"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh"
        },
        href: "https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh",
        id: "3q7HBObVc0L8jNeTe5Gofh",
        name: "50 Cent",
        type: "artist",
        uri: "spotify:artist:3q7HBObVc0L8jNeTe5Gofh"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/70gP6Ry4Uo0Yx6uzPIdaiJ"
        },
        href: "https://api.spotify.com/v1/artists/70gP6Ry4Uo0Yx6uzPIdaiJ",
        id: "70gP6Ry4Uo0Yx6uzPIdaiJ",
        name: "Bas",
        type: "artist",
        uri: "spotify:artist:70gP6Ry4Uo0Yx6uzPIdaiJ"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 271813,
    explicit: true,
    external_ids: {
      isrc: "USQX91301194"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/2O1vTF3y8Jq1XSrgSto6YL"
    },
    href: "https://api.spotify.com/v1/tracks/2O1vTF3y8Jq1XSrgSto6YL",
    id: "2O1vTF3y8Jq1XSrgSto6YL",
    is_local: false,
    name: "New York Times (feat. 50 Cent & Bas)",
    popularity: 55,
    preview_url: null,
    track_number: 18,
    type: "track",
    uri: "spotify:track:2O1vTF3y8Jq1XSrgSto6YL"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5tth2a3v0sWwV1C7bApBdX"
          },
          href: "https://api.spotify.com/v1/artists/5tth2a3v0sWwV1C7bApBdX",
          id: "5tth2a3v0sWwV1C7bApBdX",
          name: "Lil' Kim",
          type: "artist",
          uri: "spotify:artist:5tth2a3v0sWwV1C7bApBdX"
        }
      ],
      available_markets: [
        "AG",
        "AM",
        "AR",
        "AZ",
        "BB",
        "BF",
        "BO",
        "BR",
        "BS",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CL",
        "CO",
        "CR",
        "CV",
        "DM",
        "DO",
        "EC",
        "FJ",
        "FM",
        "FR",
        "GD",
        "GH",
        "GM",
        "GT",
        "GW",
        "GY",
        "HN",
        "IL",
        "IN",
        "JP",
        "KE",
        "KG",
        "KN",
        "KZ",
        "MD",
        "MN",
        "MU",
        "MX",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NP",
        "NZ",
        "PA",
        "PE",
        "PG",
        "PY",
        "SE",
        "SR",
        "SV",
        "SZ",
        "TD",
        "TJ",
        "TR",
        "TT",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VE",
        "ZA",
        "ZW"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/6UlNLXBFLqRDiKnyrF4oDE"
      },
      href: "https://api.spotify.com/v1/albums/6UlNLXBFLqRDiKnyrF4oDE",
      id: "6UlNLXBFLqRDiKnyrF4oDE",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2735262462e647f866d563de301",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e025262462e647f866d563de301",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048515262462e647f866d563de301",
          width: 64
        }
      ],
      name: "La Bella Mafia",
      release_date: "2003-03-03",
      release_date_precision: "day",
      total_tracks: 16,
      type: "album",
      uri: "spotify:album:6UlNLXBFLqRDiKnyrF4oDE"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/5tth2a3v0sWwV1C7bApBdX"
        },
        href: "https://api.spotify.com/v1/artists/5tth2a3v0sWwV1C7bApBdX",
        id: "5tth2a3v0sWwV1C7bApBdX",
        name: "Lil' Kim",
        type: "artist",
        uri: "spotify:artist:5tth2a3v0sWwV1C7bApBdX"
      }
    ],
    available_markets: [
      "AG",
      "AM",
      "AR",
      "AZ",
      "BB",
      "BF",
      "BO",
      "BR",
      "BS",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CL",
      "CO",
      "CR",
      "CV",
      "DM",
      "DO",
      "EC",
      "FJ",
      "FM",
      "FR",
      "GD",
      "GH",
      "GM",
      "GT",
      "GW",
      "GY",
      "HN",
      "IL",
      "IN",
      "JP",
      "KE",
      "KG",
      "KN",
      "KZ",
      "MD",
      "MN",
      "MU",
      "MX",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NP",
      "NZ",
      "PA",
      "PE",
      "PG",
      "PY",
      "SE",
      "SR",
      "SV",
      "SZ",
      "TD",
      "TJ",
      "TR",
      "TT",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VE",
      "ZA",
      "ZW"
    ],
    disc_number: 1,
    duration_ms: 359973,
    explicit: true,
    external_ids: {
      isrc: "USAT20300282"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/0aULRU35N9kTj6O1xMULRR"
    },
    href: "https://api.spotify.com/v1/tracks/0aULRU35N9kTj6O1xMULRR",
    id: "0aULRU35N9kTj6O1xMULRR",
    is_local: false,
    name: "Magic Stick",
    popularity: 61,
    preview_url: "https://p.scdn.co/mp3-preview/577dec47f59be0ee5fea4be83e118ddc0072f870?cid=e2ce5956a54142e3954a58845c7b9319",
    track_number: 12,
    type: "track",
    uri: "spotify:track:0aULRU35N9kTj6O1xMULRR"
  },
  {
    album: {
      album_type: "ALBUM",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/20qISvAhX20dpIbOOzGK3q"
          },
          href: "https://api.spotify.com/v1/artists/20qISvAhX20dpIbOOzGK3q",
          id: "20qISvAhX20dpIbOOzGK3q",
          name: "Nas",
          type: "artist",
          uri: "spotify:artist:20qISvAhX20dpIbOOzGK3q"
        }
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/2TcGsG6Ht4iMbEQ0u62Rbz"
      },
      href: "https://api.spotify.com/v1/albums/2TcGsG6Ht4iMbEQ0u62Rbz",
      id: "2TcGsG6Ht4iMbEQ0u62Rbz",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2732fdd2421af05fe3adda0cec7",
          width: 640
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e022fdd2421af05fe3adda0cec7",
          width: 300
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048512fdd2421af05fe3adda0cec7",
          width: 64
        }
      ],
      name: "Magic 2",
      release_date: "2023-07-21",
      release_date_precision: "day",
      total_tracks: 11,
      type: "album",
      uri: "spotify:album:2TcGsG6Ht4iMbEQ0u62Rbz"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/20qISvAhX20dpIbOOzGK3q"
        },
        href: "https://api.spotify.com/v1/artists/20qISvAhX20dpIbOOzGK3q",
        id: "20qISvAhX20dpIbOOzGK3q",
        name: "Nas",
        type: "artist",
        uri: "spotify:artist:20qISvAhX20dpIbOOzGK3q"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh"
        },
        href: "https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh",
        id: "3q7HBObVc0L8jNeTe5Gofh",
        name: "50 Cent",
        type: "artist",
        uri: "spotify:artist:3q7HBObVc0L8jNeTe5Gofh"
      }
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
    ],
    disc_number: 1,
    duration_ms: 232017,
    explicit: true,
    external_ids: {
      isrc: "QMBZ92354769"
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/7cXlDCmulkI5UWLCtSjhRF"
    },
    href: "https://api.spotify.com/v1/tracks/7cXlDCmulkI5UWLCtSjhRF",
    id: "7cXlDCmulkI5UWLCtSjhRF",
    is_local: false,
    name: "Office Hours (feat. 50 Cent)",
    popularity: 52,
    preview_url: "https://p.scdn.co/mp3-preview/2dde28009d2238a5b35e9051bec65522d237ab28?cid=e2ce5956a54142e3954a58845c7b9319",
    track_number: 3,
    type: "track",
    uri: "spotify:track:7cXlDCmulkI5UWLCtSjhRF"
  }
]
